# Generated by Django 5.2.3 on 2025-06-30 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.CharField(choices=[('电子产品', '电子产品'), ('证件卡片', '证件卡片'), ('学习用品', '学习用品'), ('生活用品', '生活用品'), ('其他', '其他')], default='其他', help_text='必须是：电子产品、证件卡片、学习用品、生活用品、其他', max_length=20, verbose_name='物品类别'),
        ),
        migrations.AddField(
            model_name='item',
            name='time',
            field=models.DateField(blank=True, help_text='格式：YYYY-MM-DD（可选）', null=True, verbose_name='事件日期'),
        ),
        migrations.AlterField(
            model_name='item',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='是否已解决'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=50, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='物品标题'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('LOST', '失物'), ('FOUND', '招领')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
