# Generated by Django 5.2.3 on 2025-07-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options_item_item_class_item_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='items.item', verbose_name='拾取物品')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='items.item', verbose_name='丢失物品')),
            ],
            options={
                'verbose_name': '匹配通知记录',
                'verbose_name_plural': '匹配通知记录',
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
